
export const UPDATE_OBJ_FAB_STATUS_REQUEST = "UPDATE_OBJ_FAB_STATUS_REQUEST";
export const UPDATE_OBJ_FAB_STATUS_SUCCESS = "UPDATE_OBJ_FAB_STATUS_SUCCESS";
export const UPDATE_OBJ_FAB_STATUS_FAILURE = "UPDATE_OBJ_FAB_STATUS_FAILURE";

export const GET_OBJ_FAB_STATUS_REQUEST = "GET_OBJ_FAB_STATUS_REQUEST";
export const GET_OBJ_FAB_STATUS_SUCCESS = "GET_OBJ_FAB_STATUS_SUCCESS";
export const GET_OBJ_FAB_STATUS_FAILURE = "GET_OBJ_FAB_STATUS_FAILURE";