export const CREATE_FAB_STATUS_REQUEST = "CREATE_FAB_STATUS_REQUEST";
export const CREATE_FAB_STATUS_SUCCESS = "CREATE_FAB_STATUS_SUCCESS";
export const CREATE_FAB_STATUS_FAILURE = "CREATE_FAB_STATUS_FAILURE";

export const GET_FAB_STATUS_REQUEST = "GET_FAB_STATUS_REQUEST";
export const GET_FAB_STATUS_SUCCESS = "GET_FAB_STATUS_SUCCESS";
export const GET_FAB_STATUS_FAILURE = "GET_FAB_STATUS_FAILURE";

export const DELETE_FAB_STATUS_REQUEST = "DELETE_FAB_STATUS_REQUEST";
export const DELETE_FAB_STATUS_SUCCESS = "DELETE_FAB_STATUS_SUCCESS";
export const DELETE_FAB_STATUS_FAILURE = "DELETE_FAB_STATUS_FAILURE";