export const CREATE_FAB_STATUS_REQUEST = "CREATE_FAB_STATUS_REQUEST";
export const CREATE_FAB_STATUS_SUCCESS = "CREATE_FAB_STATUS_SUCCESS";
export const CREATE_FAB_STATUS_FAILURE = "CREATE_FAB_STATUS_FAILURE";